# Generated by Django 2.0.7 on 2018-08-04 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20180804_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['-data_criacao']},
        ),
    ]
