# Generated by Django 2.0.7 on 2018-08-04 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20180804_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='banheiros',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='imovel',
            name='vagas_estacionamento',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='anunciante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagens',
            field=models.ManyToManyField(blank=True, to='catalogo.Foto'),
        ),
    ]
