# Generated by Django 2.0.7 on 2018-08-23 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_auto_20180805_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='anunciante',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='imagens',
            field=models.ImageField(blank=True, null=True, upload_to='media/imoveis'),
        ),
    ]
