# Generated by Django 2.0.7 on 2018-08-23 18:45

import catalogo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_auto_20180823_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to=catalogo.models.renomear_imagem),
        ),
    ]
